### ISSUE TITLE
ssh -L -nNT leads to ECONNREFUSED

### ISSUE THREAD

**Issue by GauravTiwarii** [GauravTiwarii/issue_tracking_for_cmd#4]
ssh -L 37868:st-datase.ceqgmgryf.eu-west-1.rds.amazonaws.com:5432 -nNT ec2-user@84.201.224.6 -o StrictHostKeyChecking=no -o ExitOnForwardFailure=yes

results in 
Error: connect ECONNREFUSED 127.0.0.1:37868
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1062:14)

**Comment by GauravTiwarii** [comment]
The port forwarding requires more time than 4 seconds. If you are using this command in automation process, ensure to use "sleep 4" to resolve this issue.
